apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api-db
  namespace: video-infra
  labels:
    app: video-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api-db
  template:
    metadata:
      labels:
        app: video-api-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "video_management"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: video-api-db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: video-api-db-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: video-api-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-api-db-pvc
  namespace: video-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: video-api-db
  namespace: video-infra
spec:
  selector:
    app: video-api-db
  ports:
    - port: 5432
      targetPort: 5432
